### ISSUE TITLE
Client and server need to standardize passing of user info

### ISSUE THREAD

**Issue by gloriama** [laudatory-flannel/laudatory-flannel#34]
Server currently uses /users/:id to denote which user's friends to populate
But with JWT, client will be able to directly denote who they are

**Comment by rachelrf** [comment]
I think this is going to be one of the biggest things today

**Comment by rachelrf** [comment]
need to save user to localstorage

**Comment by rachelrf** [comment]
Auth is part of this

**Comment by rachelrf** [comment]
work around using localStorage
